use serde::{Serialize, Deserialize};
use std::str::FromStr;

pub type SettlementCurrency = Currency;
pub type QuoteCurrency = Currency;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, bincode::Decode, bincode::Encode)]
pub enum Currency {
    USD,
    USDT,
    USDC,
    USDE,
    BTC,
    ETH,
    SOL,
    BNB,
    ADA,
    XRP,
    DOGE,
    TRX,
    LINK,
    AVAX,
    DOT,
    LTC,
    BCH,
    UNI,
    NEAR,
    SHIB,
    SUIT,
    HBAR,
    SUI,
    TON,
    AAVE,
    TAO,
    XLM,
    XMR,
    ZEC,
    HYPE,
    DAI,
    EUR,
    BRL,
    PLN,
    TRY,
    MNT,
    XUSD,
    RLUSD,
    GBP,
    CAD,
    AUD,
    JPY,
    CHF,
}

impl FromStr for Currency {
    type Err = ();
    
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "BTC" | "XBT" => Ok(Currency::BTC),
            "ETH" => Ok(Currency::ETH),
            "SOL" => Ok(Currency::SOL),
            "XRP" => Ok(Currency::XRP),
            "BNB" => Ok(Currency::BNB),
            "ADA" => Ok(Currency::ADA),
            "DOGE" => Ok(Currency::DOGE),
            "TRX" => Ok(Currency::TRX),
            "LINK" => Ok(Currency::LINK),
            "AVAX" => Ok(Currency::AVAX),
            "DOT" => Ok(Currency::DOT),
            "LTC" => Ok(Currency::LTC),
            "BCH" => Ok(Currency::BCH),
            "UNI" => Ok(Currency::UNI),
            "NEAR" => Ok(Currency::NEAR),
            "SHIB" => Ok(Currency::SHIB),
            "SUI" => Ok(Currency::SUI),
            "HBAR" => Ok(Currency::HBAR),
            "TON" => Ok(Currency::TON),
            "AAVE" => Ok(Currency::AAVE),
            "TAO" => Ok(Currency::TAO),
            "XLM" => Ok(Currency::XLM),
            "XMR" => Ok(Currency::XMR),
            "ZEC" => Ok(Currency::ZEC),
            "HYPE" => Ok(Currency::HYPE),
            "USD" => Ok(Currency::USD),
            "USDT" => Ok(Currency::USDT),
            "USDC" => Ok(Currency::USDC),
            "DAI" => Ok(Currency::DAI),
            "EUR" => Ok(Currency::EUR),
            "USDE" => Ok(Currency::USDE),
            "BRL" => Ok(Currency::BRL),
            "PLN" => Ok(Currency::PLN),
            "TRY" => Ok(Currency::TRY),
            "MNT" => Ok(Currency::MNT),
            "XUSD" => Ok(Currency::XUSD),
            "RLUSD" => Ok(Currency::RLUSD),
            "GBP" => Ok(Currency::GBP),
            "CAD" => Ok(Currency::CAD),
            "AUD" => Ok(Currency::AUD),
            "JPY" => Ok(Currency::JPY),
            "ZUSD" => Ok(Currency::USD),
            "ZEUR" => Ok(Currency::EUR),
            "ZGBP" => Ok(Currency::GBP),
            "ZCAD" => Ok(Currency::CAD),
            "ZAUD" => Ok(Currency::AUD),
            "ZJPY" => Ok(Currency::JPY),
            "XXBT" => Ok(Currency::BTC),
            "XETH" => Ok(Currency::ETH),
            "CHF" => Ok(Currency::CHF),
            "USD_UM" => Ok(Currency::USD),
            _ => Err(()),
        }
    }
}

//["BTC", "ETH", "SOL", "XRP", "BNB", "DOGE", "ZEC", "ADA", "SUI", "BCH", "TRX", "LINK", "AVAX", "XAUt", "PAXG", "LTC", "UNI", "PEPE", "AAVE", "HYPE", "DOT", "NEAR", "TON", "ENA", "ASTER"])